# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Language-AttributeGrammar
version:      0.08
version_from: lib/Language/AttributeGrammar.pm
installdirs:  site
requires:
    Carp::Clan:                    0
    Parse::RecDescent:             0
    Perl6::Attributes:             0
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
