# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Placeholders
version:      0.07
version_from: 
installdirs:  site
requires:
    Filter::Simple:                0.78

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
