# This Makefile is for the Glop extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.12 (Revision: 1.124) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     ABSTRACT_FROM => q[Glop.pm]
#     AUTHOR => q[Luke Palmer <fibonaci@nonet>]
#     NAME => q[Glop]
#     PREREQ_PM => { Filter::Simple=>q[0], Want=>q[0], SDL=>q[1.20], ODE=>q[0] }
#     VERSION_FROM => q[Glop.pm]

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /System/Library/Perl/5.8.1/darwin-thread-multi-2level/Config.pm)

# They may have been overridden via Makefile.PL or on the command line
AR = ar
CC = cc
CCCDLFLAGS =  
CCDLFLAGS =  
DLEXT = bundle
DLSRC = dl_dyld.xs
LD = MACOSX_DEPLOYMENT_TARGET=10.3 cc
LDDLFLAGS = -bundle -undefined dynamic_lookup -L/usr/local/lib
LDFLAGS = -L/usr/local/lib
LIBC = /usr/lib/libc.dylib
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = darwin
OSVERS = 7.0
RANLIB = /usr/bin/ar ts
SITELIBEXP = /Library/Perl/5.8.1
SITEARCHEXP = /Library/Perl/5.8.1/darwin-thread-multi-2level
SO = dylib
EXE_EXT = 
FULL_AR = /usr/bin/ar
VENDORARCHEXP = /Network/Library/Perl/5.8.1/darwin-thread-multi-2level
VENDORLIBEXP = /Network/Library/Perl/5.8.1


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
NAME = Glop
NAME_SYM = Glop
VERSION = 0.01
VERSION_MACRO = VERSION
VERSION_SYM = 0_01
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 0.01
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = ../blib/arch
INST_SCRIPT = ../blib/script
INST_BIN = ../blib/bin
INST_LIB = ../blib/lib
INST_MAN1DIR = ../blib/man1
INST_MAN3DIR = ../blib/man3
MAN1EXT = 1
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = 
PERLPREFIX = /
SITEPREFIX = /
VENDORPREFIX = /usr/local
INSTALLPRIVLIB = $(PERLPREFIX)//System/Library/Perl/5.8.1
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = $(SITEPREFIX)//Library/Perl/5.8.1
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /Network/Library/Perl/5.8.1
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = $(PERLPREFIX)//System/Library/Perl/5.8.1/darwin-thread-multi-2level
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = $(SITEPREFIX)//Library/Perl/5.8.1/darwin-thread-multi-2level
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /Network/Library/Perl/5.8.1/darwin-thread-multi-2level
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = $(PERLPREFIX)//usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = $(SITEPREFIX)//usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = $(VENDORPREFIX)/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = $(PERLPREFIX)//usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLMAN1DIR = $(PERLPREFIX)//usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = $(SITEPREFIX)//man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = $(VENDORPREFIX)/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = $(PERLPREFIX)//usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = $(SITEPREFIX)//man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = $(VENDORPREFIX)/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /System/Library/Perl/5.8.1
PERL_ARCHLIB = /System/Library/Perl/5.8.1/darwin-thread-multi-2level
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = $(FIRST_MAKEFILE).old
MAKE_APERL_FILE = $(FIRST_MAKEFILE).aperl
PERLMAINCC = $(CC)
PERL_INC = /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /System/Library/Perl/5.8.1/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.12
MM_REVISION = 1.124

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
FULLEXT = Glop
BASEEXT = Glop
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = Glop.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = Glop.pm \
	Glop/Draw/Circle.pm \
	Glop/Draw/Rect.pm \
	Glop/Draw/Sprite.pm \
	Glop/Draw/Text.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DIRFILESEP)Config.pm $(PERL_INC)$(DIRFILESEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = Glop.pm \
	Glop/Actor.pm \
	Glop/Agent.pm \
	Glop/Agent/InputBox.pm \
	Glop/Agent/Menu.pm \
	Glop/AutoGL.pm \
	Glop/AutoMethod.pm \
	Glop/DisplayList.pm \
	Glop/Draw.pm \
	Glop/Draw/Circle.pm \
	Glop/Draw/Rect.pm \
	Glop/Draw/Sprite.pm \
	Glop/Draw/Text.pm \
	Glop/Draw/fonts/aircut3.ttf \
	Glop/Floater.pm \
	Glop/Floater/A.pm \
	Glop/Floater/Timed.pm \
	Glop/Floater/Timer.pm \
	Glop/Input.pm \
	Glop/Input/Backend/SDL.pm \
	Glop/Input/Key.pm \
	Glop/Input/KeyNames.pm \
	Glop/Input/KeyState.pm \
	Glop/Input/Mouse.pm \
	Glop/Kernel.pm \
	Glop/Physics.pm \
	Glop/Role.pm \
	Glop/Role/Body.pm \
	Glop/Role/Geom.pm \
	Glop/Texture.pm \
	Glop/Transient.pm \
	Glop/Transient/Timed.pm \
	Glop/TransientQueue.pm

PM_TO_BLIB = Glop/Role.pm \
	$(INST_LIB)/Glop/Role.pm \
	Glop/DisplayList.pm \
	$(INST_LIB)/Glop/DisplayList.pm \
	Glop/Kernel.pm \
	$(INST_LIB)/Glop/Kernel.pm \
	Glop/Input.pm \
	$(INST_LIB)/Glop/Input.pm \
	Glop/Input/Key.pm \
	$(INST_LIB)/Glop/Input/Key.pm \
	Glop/Input/KeyState.pm \
	$(INST_LIB)/Glop/Input/KeyState.pm \
	Glop/Agent/InputBox.pm \
	$(INST_LIB)/Glop/Agent/InputBox.pm \
	Glop/Agent.pm \
	$(INST_LIB)/Glop/Agent.pm \
	Glop/Draw/Sprite.pm \
	$(INST_LIB)/Glop/Draw/Sprite.pm \
	Glop.pm \
	$(INST_LIB)/Glop.pm \
	Glop/Physics.pm \
	$(INST_LIB)/Glop/Physics.pm \
	Glop/Role/Geom.pm \
	$(INST_LIB)/Glop/Role/Geom.pm \
	Glop/Draw/fonts/aircut3.ttf \
	$(INST_LIB)/Glop/Draw/fonts/aircut3.ttf \
	Glop/Draw.pm \
	$(INST_LIB)/Glop/Draw.pm \
	Glop/Floater/Timed.pm \
	$(INST_LIB)/Glop/Floater/Timed.pm \
	Glop/Role/Body.pm \
	$(INST_LIB)/Glop/Role/Body.pm \
	Glop/Draw/Text.pm \
	$(INST_LIB)/Glop/Draw/Text.pm \
	Glop/Draw/Circle.pm \
	$(INST_LIB)/Glop/Draw/Circle.pm \
	Glop/Actor.pm \
	$(INST_LIB)/Glop/Actor.pm \
	Glop/AutoMethod.pm \
	$(INST_LIB)/Glop/AutoMethod.pm \
	Glop/Agent/Menu.pm \
	$(INST_LIB)/Glop/Agent/Menu.pm \
	Glop/Input/Backend/SDL.pm \
	$(INST_LIB)/Glop/Input/Backend/SDL.pm \
	Glop/Floater/Timer.pm \
	$(INST_LIB)/Glop/Floater/Timer.pm \
	Glop/Texture.pm \
	$(INST_LIB)/Glop/Texture.pm \
	Glop/Floater/A.pm \
	$(INST_LIB)/Glop/Floater/A.pm \
	Glop/AutoGL.pm \
	$(INST_LIB)/Glop/AutoGL.pm \
	Glop/Input/KeyNames.pm \
	$(INST_LIB)/Glop/Input/KeyNames.pm \
	Glop/TransientQueue.pm \
	$(INST_LIB)/Glop/TransientQueue.pm \
	Glop/Input/Mouse.pm \
	$(INST_LIB)/Glop/Input/Mouse.pm \
	Glop/Floater.pm \
	$(INST_LIB)/Glop/Floater.pm \
	Glop/Transient.pm \
	$(INST_LIB)/Glop/Transient.pm \
	Glop/Transient/Timed.pm \
	$(INST_LIB)/Glop/Transient/Timed.pm \
	Glop/Draw/Rect.pm \
	$(INST_LIB)/Glop/Draw/Rect.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 1.39
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(PERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)'



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(SHELL) -c true
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(PERLRUN) "-MExtUtils::Command" -e mkpath
EQUALIZE_TIMESTAMP = $(PERLRUN) "-MExtUtils::Command" -e eqtime
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(PERLRUN) -MExtUtils::Install -e 'install({@ARGV}, '\''$(VERBINST)'\'', 0, '\''$(UNINST)'\'');'
DOC_INSTALL = $(PERLRUN) "-MExtUtils::Command::MM" -e perllocal_install
UNINSTALL = $(PERLRUN) "-MExtUtils::Command::MM" -e uninstall
WARN_IF_OLD_PACKLIST = $(PERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist


# --- MakeMaker makemakerdflt section:
makemakerdflt: all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section skipped.

# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIB="$(LIB)"\
	LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"\
	OPTIMIZE="$(OPTIMIZE)"\
	PASTHRU_DEFINE="$(PASTHRU_DEFINE)"\
	PASTHRU_INC="$(PASTHRU_INC)"


# --- MakeMaker special_targets section:
.SUFFIXES: .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) $(INST_LIBDIR)$(DIRFILESEP).exists
	$(NOECHO) $(NOOP)

config :: $(INST_ARCHAUTODIR)$(DIRFILESEP).exists
	$(NOECHO) $(NOOP)

config :: $(INST_AUTODIR)$(DIRFILESEP).exists
	$(NOECHO) $(NOOP)

$(INST_AUTODIR)/.exists :: /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(EQUALIZE_TIMESTAMP) /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h $(INST_AUTODIR)/.exists

	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_AUTODIR)

$(INST_LIBDIR)/.exists :: /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(EQUALIZE_TIMESTAMP) /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h $(INST_LIBDIR)/.exists

	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_LIBDIR)

$(INST_ARCHAUTODIR)/.exists :: /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(EQUALIZE_TIMESTAMP) /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h $(INST_ARCHAUTODIR)/.exists

	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_ARCHAUTODIR)

config :: $(INST_MAN3DIR)$(DIRFILESEP).exists
	$(NOECHO) $(NOOP)


$(INST_MAN3DIR)/.exists :: /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(EQUALIZE_TIMESTAMP) /System/Library/Perl/5.8.1/darwin-thread-multi-2level/CORE/perl.h $(INST_MAN3DIR)/.exists

	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_MAN3DIR)

help:
	perldoc ExtUtils::MakeMaker


# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make dynamic"
dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

# --- Begin manifypods section:
POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"


manifypods : pure_all  \
	Glop/Draw/Text.pm \
	Glop/Draw/Sprite.pm \
	Glop.pm \
	Glop/Draw/Circle.pm \
	Glop/Draw/Rect.pm \
	Glop/Draw/Text.pm \
	Glop/Draw/Sprite.pm \
	Glop.pm \
	Glop/Draw/Circle.pm \
	Glop/Draw/Rect.pm
	$(NOECHO) $(POD2MAN_EXE) --section=3 --perm_rw=$(PERM_RW)\
	  Glop/Draw/Text.pm $(INST_MAN3DIR)/Glop::Draw::Text.$(MAN3EXT) \
	  Glop/Draw/Sprite.pm $(INST_MAN3DIR)/Glop::Draw::Sprite.$(MAN3EXT) \
	  Glop.pm $(INST_MAN3DIR)/Glop.$(MAN3EXT) \
	  Glop/Draw/Circle.pm $(INST_MAN3DIR)/Glop::Draw::Circle.$(MAN3EXT) \
	  Glop/Draw/Rect.pm $(INST_MAN3DIR)/Glop::Draw::Rect.$(MAN3EXT) 


# --- End manifypods section --- #



# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	-$(RM_RF) ./blib $(MAKE_APERL_FILE) $(INST_ARCHAUTODIR)/extralibs.all perlmain.c tmon.out mon.out so_locations pm_to_blib *$(OBJ_EXT) *$(LIB_EXT) perl.exe perl perl$(EXE_EXT) $(BOOTSTRAP) $(BASEEXT).bso $(BASEEXT).def lib$(BASEEXT).def $(BASEEXT).exp $(BASEEXT).x core core.*perl.*.? *perl.core core.[0-9] core.[0-9][0-9] core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9][0-9]
	-$(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:

# Delete temporary files (via clean) and also delete installed files
realclean purge ::  clean realclean_subdirs
	$(RM_RF) $(INST_AUTODIR) $(INST_ARCHAUTODIR)
	$(RM_RF) $(DISTVNAME)
	$(RM_F)  $(INST_LIB)/Glop/Input/Backend/SDL.pm $(INST_LIB)/Glop/Role/Geom.pm $(MAKEFILE_OLD) $(INST_LIB)/Glop/AutoMethod.pm $(INST_LIB)/Glop/DisplayList.pm $(INST_LIB)/Glop/TransientQueue.pm
	$(RM_F) $(INST_LIB)/Glop/Floater/Timer.pm $(INST_LIB)/Glop/Draw/Sprite.pm $(INST_LIB)/Glop/Draw/Text.pm $(INST_LIB)/Glop/Physics.pm $(INST_LIB)/Glop/Role/Body.pm $(INST_LIB)/Glop/Floater.pm
	$(RM_F) $(INST_LIB)/Glop/Draw/Circle.pm $(INST_LIB)/Glop/Transient.pm $(INST_LIB)/Glop/Agent.pm $(INST_LIB)/Glop/Actor.pm $(INST_LIB)/Glop/Input/KeyNames.pm $(INST_LIB)/Glop/Transient/Timed.pm
	$(RM_F) $(INST_LIB)/Glop/Input.pm $(INST_LIB)/Glop/Draw/fonts/aircut3.ttf $(INST_LIB)/Glop/AutoGL.pm $(INST_LIB)/Glop/Input/Mouse.pm $(INST_LIB)/Glop/Kernel.pm $(INST_LIB)/Glop/Agent/Menu.pm
	$(RM_F) $(INST_LIB)/Glop.pm $(INST_LIB)/Glop/Draw/Rect.pm $(INST_LIB)/Glop/Agent/InputBox.pm $(FIRST_MAKEFILE) $(INST_LIB)/Glop/Input/KeyState.pm $(INST_LIB)/Glop/Texture.pm $(INST_LIB)/Glop/Floater/A.pm
	$(RM_F) $(INST_LIB)/Glop/Floater/Timed.pm $(INST_LIB)/Glop/Draw.pm $(INST_LIB)/Glop/Role.pm $(INST_LIB)/Glop/Input/Key.pm


# --- MakeMaker metafile section:
metafile :
	$(NOECHO) $(ECHO) '#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#' > META.yml
	$(NOECHO) $(ECHO) 'name:         Glop' >> META.yml
	$(NOECHO) $(ECHO) 'version:      0.01' >> META.yml
	$(NOECHO) $(ECHO) 'version_from: Glop.pm' >> META.yml
	$(NOECHO) $(ECHO) 'installdirs:  site' >> META.yml
	$(NOECHO) $(ECHO) 'requires:' >> META.yml
	$(NOECHO) $(ECHO) '    Filter::Simple:                0' >> META.yml
	$(NOECHO) $(ECHO) '    Want:                          0' >> META.yml
	$(NOECHO) $(ECHO) '    SDL:                           1.20' >> META.yml
	$(NOECHO) $(ECHO) '    ODE:                           0' >> META.yml
	$(NOECHO) $(ECHO) '' >> META.yml
	$(NOECHO) $(ECHO) 'distribution_type: module' >> META.yml
	$(NOECHO) $(ECHO) 'generated_by: ExtUtils::MakeMaker version 6.12' >> META.yml


# --- MakeMaker metafile_addtomanifest section:
metafile_addtomanifest:
	$(NOECHO) $(PERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	-e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"'


# --- MakeMaker dist_basics section skipped.

# --- MakeMaker dist_core section skipped.

# --- MakeMaker distdir section skipped.

# --- MakeMaker dist_test section skipped.

# --- MakeMaker dist_ci section skipped.

# --- MakeMaker install section skipped.

# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE:
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:

# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	-$(MAKE) -f $(MAKEFILE_OLD) clean $(DEV_NULL) || $(NOOP)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the make command.  <=="
	false



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = ../perl
FULLPERL      = /usr/bin/perl


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE)

test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd:
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="0,01,0,0">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <TITLE>$(DISTNAME)</TITLE>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>Game Language Of Perl</ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>Luke Palmer &lt;fibonaci@nonet&gt;</AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Filter-Simple" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="ODE" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="SDL" VERSION="1,20,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Want" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <OS NAME="$(OSNAME)" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="darwin-thread-multi-2level" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib: $(TO_INST_PM)
	$(NOECHO) $(PERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', '\''$(PM_FILTER)'\'')'\
	  Glop/Role.pm $(INST_LIB)/Glop/Role.pm \
	  Glop/DisplayList.pm $(INST_LIB)/Glop/DisplayList.pm \
	  Glop/Kernel.pm $(INST_LIB)/Glop/Kernel.pm \
	  Glop/Input.pm $(INST_LIB)/Glop/Input.pm \
	  Glop/Input/Key.pm $(INST_LIB)/Glop/Input/Key.pm \
	  Glop/Input/KeyState.pm $(INST_LIB)/Glop/Input/KeyState.pm \
	  Glop/Agent/InputBox.pm $(INST_LIB)/Glop/Agent/InputBox.pm \
	  Glop/Agent.pm $(INST_LIB)/Glop/Agent.pm \
	  Glop/Draw/Sprite.pm $(INST_LIB)/Glop/Draw/Sprite.pm \
	  Glop.pm $(INST_LIB)/Glop.pm \
	  Glop/Physics.pm $(INST_LIB)/Glop/Physics.pm \
	  Glop/Role/Geom.pm $(INST_LIB)/Glop/Role/Geom.pm \
	  Glop/Draw/fonts/aircut3.ttf $(INST_LIB)/Glop/Draw/fonts/aircut3.ttf \
	  Glop/Draw.pm $(INST_LIB)/Glop/Draw.pm \
	  Glop/Floater/Timed.pm $(INST_LIB)/Glop/Floater/Timed.pm \
	  Glop/Role/Body.pm $(INST_LIB)/Glop/Role/Body.pm \
	  Glop/Draw/Text.pm $(INST_LIB)/Glop/Draw/Text.pm \
	  Glop/Draw/Circle.pm $(INST_LIB)/Glop/Draw/Circle.pm \
	  Glop/Actor.pm $(INST_LIB)/Glop/Actor.pm \
	  Glop/AutoMethod.pm $(INST_LIB)/Glop/AutoMethod.pm \
	  Glop/Agent/Menu.pm $(INST_LIB)/Glop/Agent/Menu.pm \
	  Glop/Input/Backend/SDL.pm $(INST_LIB)/Glop/Input/Backend/SDL.pm \
	  Glop/Floater/Timer.pm $(INST_LIB)/Glop/Floater/Timer.pm \
	  Glop/Texture.pm $(INST_LIB)/Glop/Texture.pm \
	  Glop/Floater/A.pm $(INST_LIB)/Glop/Floater/A.pm \
	  Glop/AutoGL.pm $(INST_LIB)/Glop/AutoGL.pm \
	  Glop/Input/KeyNames.pm $(INST_LIB)/Glop/Input/KeyNames.pm \
	  Glop/TransientQueue.pm $(INST_LIB)/Glop/TransientQueue.pm \
	  Glop/Input/Mouse.pm $(INST_LIB)/Glop/Input/Mouse.pm \
	  Glop/Floater.pm $(INST_LIB)/Glop/Floater.pm \
	  Glop/Transient.pm $(INST_LIB)/Glop/Transient.pm \
	  Glop/Transient/Timed.pm $(INST_LIB)/Glop/Transient/Timed.pm \
	  Glop/Draw/Rect.pm $(INST_LIB)/Glop/Draw/Rect.pm 
	$(NOECHO) $(TOUCH) $@

# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
