# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Logic
version:      0.02
version_from: lib/Logic.pm
installdirs:  site
requires:
    Attribute::Handlers:           0
    Devel::Caller::Perl:           0
    Filter::Simple:                0
    Perl6::Attributes:             0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
