# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Attributes
version:      0.04
version_from: lib/Perl6/Attributes.pm
installdirs:  site
requires:
    Filter::Simple:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
