package com.learningrx.ComprehensionFigures
{
	import com.learningrx.*;

	public class RulesAndDefinitions
	{
		public static const TURNS_PER_ROUND:Number = 10;
		public static const RIGHT_ANSWER_PAUSE_SECONDS:Number = .5;
		public static const WRONG_ANSWER_PAUSE_SECONDS:Number = 1;
		public static const SPEEDS:Array = [30, 25, 20, 15];
		public static const TURN_NUM_TO_HIDE_KEY:Number = 3;
		public static const SUBLEVEL_TO_HIDE_KEY:Number = 1;
		public static const SUBLEVEL_TO_HIDE_FIND_TEXT:Number = 1
		public static const TURN_TIMER_INTERVAL:Number = 100; // lower means smoother animation
		public static const NUMBER_OF_ANSWER_BOXES:Number = 4;

		public static const LEVELS:Object = {
		1: {NumberOfFigures: 2, FigureType: 'object', Positions: [1],
		    DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		2:	{NumberOfFigures: 2, FigureType: 'object', Positions: [4],
		    DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		3: {NumberOfFigures: 2, FigureType: 'object', Positions: [4],
		    DescriptionTypes: ["name", "description"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		4: {NumberOfFigures: 2, FigureType: 'shape', Positions: [1],
			 DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		5: {NumberOfFigures: 2, FigureType: 'shape', Positions: [2],
		    DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		6: {NumberOfFigures: 2, FigureType: 'shape', Positions: [1, 2],
		    DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		7: {NumberOfFigures: 2, FigureType: 'shape', Positions: [1, 2],
		    DescriptionTypes: ["name"], Represent: "object",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		8: {NumberOfFigures: 2, FigureType: 'shape', Positions: [1, 2],
		    DescriptionTypes: ["name", "description"], Represent: "object",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		9: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2], 
		    DescriptionTypes: ["name"], Represent: "self",
			 Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN}}},
		10: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2],
		     DescriptionTypes: ["name", "description"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		11: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3],
		     DescriptionTypes: ["name", "description"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		12: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3], 
		     DescriptionTypes: ["name"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		13: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		14: {NumberOfFigures: 3, FigureType: 'abstract', Positions: [1, 2, 3], 
		     DescriptionTypes: ["name"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		15: {NumberOfFigures: 3, FigureType: 'abstract', Positions: [1, 2, 3], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		16: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3, 4], 
		     DescriptionTypes: ["name"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		17: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3, 4], 
		     DescriptionTypes: ["name", "description"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		18: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3, 4], 
		     DescriptionTypes: ["name"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		19: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3, 4], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		20: {NumberOfFigures: 3, FigureType: 'abstract', Positions: [1, 2, 3, 4], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		21: {NumberOfFigures: 3, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description", "function"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		22: {NumberOfFigures: 3, FigureType: 'abstract', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description", "function"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		23: {NumberOfFigures: 4, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		24: {NumberOfFigures: 4, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description"], Represent: "self",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		25: {NumberOfFigures: 4, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		26: {NumberOfFigures: 4, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		27: {NumberOfFigures: 4, FigureType: 'abstract', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		28: {NumberOfFigures: 4, FigureType: 'shape', Positions: [1, 2, 3, 4, 5], 
		     DescriptionTypes: ["name", "description", "function"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}},
		29: {NumberOfFigures: 4, FigureType: 'abstract', Positions: [1, 2, 3, 4, 5], 
			  DescriptionTypes: ["name", "description", "function"], Represent: "object",
			  Sublevels: {1: {TurnToHideKey: NaN, SecondsToHideFindText: NaN},
			              2: {TurnToHideKey: NaN, SecondsToHideFindText: 5},
							  3: {TurnToHideKey: 3, SecondsToHideFindText: 5}}}};
			 
		public static const POSITIONS:Object = {
			1: [{FunctionName: "Above", Text: ["above"]}, 
				 {FunctionName: "Below", Text: ["below"]}],
			2: [{FunctionName: "Inside", Text: ["inside"]}, 
			    {FunctionName: "Around", Text: ["around"]}],
			3: [{FunctionName: "Left", Text: ["to the left of"]}, 
				 {FunctionName: "Right", Text: ["to the right of"]}],
			4: [{FunctionName: "Higher", Text: ["higher than"]},
				 {FunctionName: "Lower", Text: ["lower than"]}],
			5: [{FunctionName: "Overlapping", Text: ["overlapping"]}, 
				 {FunctionName: "Touching", Text: ["touching"]}, 
				 {FunctionName: "Intersecting", Text: ["intersecting"]},
				 {FunctionName: "Behind", Text: ["behind"]}, 
				 {FunctionName: "InFrontOf", Text: ["in front of"]}]};

		public static const OBJECTS:Array = [
			{Name: 'balloon',
			 Descriptions: ['something you fill with air', 'an object that gets bigger when you blow into it'], 
			 Functions: ['an object you fill with water and throw', 'an object that floats']}, 
			{Name: 'bush', 
			 Descriptions: ['a green plant in your yard', 'something you plant'], 
			 Functions: ['something that decorates your yard', 'an object that grows']}, 
			{Name: 'cake', 
			 Descriptions: ['something you frost', 'an object with candles'], 
			 Functions: ['something you eat', 'something used to celebrate a birthday']}, 
			{Name: 'car', 
			 Descriptions: ['an object with four wheels', 'a thing made out of mostly metal'], 
			 Functions: ['something you ride in', 'something that gets you from one place to another']}, 
			{Name: 'chicken', 
			 Descriptions: ['a barnyard animal that pecks', 'an object with feathers'], 
			 Functions: ['an animal that lays eggs', 'something you may eat for dinner']}, 
			{Name: 'clock', 
			 Descriptions: ['an object a face and hands', 'something with an alarm'], 
			 Functions: ['an object that tells time', 'something with an alarm']}, 
			{Name: 'computer', 
			 Descriptions: ['an electronic device with a screen and keyboard', 'a programmable electronic machine'], 
			 Functions: ['a device you use to surf the Internet', 'an electronic device that helps you do your homework']}, 
			{Name: 'cup', 
			 Descriptions: ['something that holds a drink', 'an object that is stored in a cupboard'], 
			 Functions: ['an object you drink from', 'an object that holds coffee']}, 
			{Name: 'elephant', 
			 Descriptions: ['a very large animal', 'an animal with a trunk'], 
			 Functions: ['an animal seen at a circus', 'an animal with a trunk']}, 
			{Name: 'fish', 
			 Descriptions: ['something that has gills', 'something that lives in water'], 
			 Functions: ['something you eat', 'something that swims']}, 
			{Name: 'glove', 
			 Descriptions: ['something you wear on your hand', 'something to keep a hand warm'], 
			 Functions: ['something worn on your hands', 'something that keeps your fingers warm']}, 
			{Name: 'hat', 
			 Descriptions: ['something you put on your head', 'an object sometimes also called a cap'], 
			 Functions: ['an object that covers your head', 'an object that shades your eyes']}, 
			{Name: 'house', 
			 Descriptions: ['an object with a roof', 'something with a front door'], 
			 Functions: ['something you live in', 'a place where you sleep']}, 
			{Name: 'light bulb', 
			 Descriptions: ['an object you turn on', 'an object made of glass'], 
			 Functions: ['an object that shines light', 'an object that burns out']}, 
			{Name: 'piggy bank', 
			 Descriptions: ['an object you place your coins in', 'an object that stores money'], 
			 Functions: ['an object that stores money', 'an object you put money into']}, 
			{Name: 'ring', 
			 Descriptions: ['an object you wear on your finger', 'an object you give when getting married'], 
			 Functions: ['something worn on a finger', 'an object that shows you are married']}, 
			{Name: 'shoe', 
			 Descriptions: ['an object that has a sole', 'an object that has laces'], 
			 Functions: ['something that protects your foot', 'something you walk in']}, 
			{Name: 'shorts', 
			 Descriptions: ['an item of clothing', 'pants that are not long'], 
			 Functions: ['something you wear', 'something you wash']}, 
			{Name: 'suitcase', 
			 Descriptions: ['something to take traveling', 'something you pack'], 
			 Functions: ['something you use to travel', 'something that carries your clothes']}, 
			{Name: 'telephone', 
			 Descriptions: ['an object with numbered buttons', 'an object that rings'], 
			 Functions: ['a device for making calls', 'aomething you use to talk to someone']}, 
			{Name: 'TV', 
			 Descriptions: ['an object with a picture screen', 'an object you turn on and off'], 
			 Functions: ['an object you watch', 'an object for watching the news']}];

		public static const SHAPES:Array = [
			{Name: 'circle', 
			 Descriptions: ['a round thing', 'a shape with no corners', 'something with no beginning and no end']}, 
			{Name: 'square', 
			 Descriptions: ['a shape with four equal sides', 'a thing with four corners']}, 
			{Name: 'star', 
			 Descriptions: ['something that shines at night', 'something you see in the sky at night']}, 
			{Name: 'sun burst', 
			 Descriptions: ['a shape like the sun']}, 
			{Name: 'rounded square', 
			 Descriptions: ['a square with round corners']}, 
			{Name: 'octagon', 
			 Descriptions: ['a shape with eight sides', 'the shape of a stop sign']}];
 	}
}